### ISSUE TITLE
UML processes with DataFrame backend

### ISSUE THREAD

**Issue by mirestrepo** [JuliaHealth/BioMedQuery.jl#26]
Right now most of the processes that involve UMLS queries support only a MySQL backend. It would be neat to have all work only with DataFrames

**Comment by DilumAluthge** [comment]
Once Query.jl supports MySQL, it might be easier to run all queries through them, which would give access to a lot of different backend.

(Currently the only SQL backend that Query.jl supports is SQLite.)

**Comment by DilumAluthge** [comment]
Disregard my previous comment. I think we should go ahead and support for DataFrames as a backend (instead of waiting on development of Query.jl).

Once we have support for DataFrames as a backend, we automatically get support for a whole lot of other backends via IterableTables.jl.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mirestrepo** [comment]
This has already been implemented by Mary. We're waiting on few internal tests to tag

**Comment by mirestrepo** [comment]
Actually - I'll close this since it's already part of master

**Comment by mcmcgrath13** [comment]
UMLS doesn't have a pure dataframe backend option yet, but I'll probably be incorporating this as part of the needed updates for PubMed Miner

**Comment by mcmcgrath13** [comment]
#34
